import{a as v,i as f,S as M}from"./assets/vendor-b2578120.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();async function m(r,s,t){const n="https://pixabay.com/",e="api/",o=new URLSearchParams({key:"43016560-45bd583880e427992fd0250d3",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t}),i=`${n}${e}?${o}`;return(await v.get(i)).data}function g(r){return r.length===0?(f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",theme:"dark"}),""):r.map(t=>`<li class="pictures-list-item">
        <a class="picture-link" href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" class="picture" />
        </a>
        <ul class="picture-data-list">
          <li class="picture-data-item"><p class="picture-inf">Likes</p><p class = "picture-inf-data">${t.likes}</p></li>
          <li class="picture-data-item"><p class="picture-inf">Views</p><p class = "picture-inf-data">${t.views}</p></li>
          <li class="picture-data-item"><p class="picture-inf">Comments</p><p class = "picture-inf-data">${t.comments}</p></li>
          <li class="picture-data-item"><p class="picture-inf">Downloads</p><p class = "picture-inf-data">${t.downloads}</p></li>
        </ul>
      </li>`).join("")}const p=document.querySelector(".search-photo"),u=document.querySelector(".pictures-list"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-button"),L=new M(".pictures-list a",{captionsData:"alt",captionDelay:250});let c="",a=1,l=0;const d=15;p.addEventListener("submit",$);h.addEventListener("click",q);async function $(r){if(r.preventDefault(),u.innerHTML="",P(),a=1,c=p.search.value.toLowerCase().trim(),c!=""){try{w();const s=await m(c,a,d),t=s.hits;l=Math.ceil(s.totalHits/d),u.insertAdjacentHTML("beforeend",g(t)),L.refresh()}catch(s){console.log(s)}b(),l!==0&&S(),p.reset()}else l=0,f.error({message:"Please enter valid query.",position:"topRight",theme:"dark"})}async function q(r){++a;try{w();const t=(await m(c,a,d)).hits;u.insertAdjacentHTML("beforeend",g(t)),L.refresh()}catch(s){console.log(s)}k(),b(),S()}function w(){y.style.display="inline-block"}function b(){y.style.display="none"}function B(){h.classList.remove("hidden")}function P(){h.classList.add("hidden")}function S(){a>=l?(P(),f.info({message:"We're sorry, but you've reached the end of search results."})):B()}function k(){const r=u.firstChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
